sonar.projectKey=hellenjrubioc-diagnosys_pruebas-diagnosys
sonar.organization=hellenjrubioc-diagnosys


# URL del servidor SonarCloud
sonar.host.url=https://sonarcloud.io

# Lenguaje del proyecto
sonar.language=ts

# Carpeta donde está el código fuente 
sonar.sources=src

# Carpeta con tests si aplica
# sonar.tests=tests

# Carpeta con archivos excluidos si aplica
# sonar.exclusions=node_modules/**,**/*.spec.ts

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=Pruebas DiagnoSys
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8