# Identificador único del proyecto en SonarCloud
sonar.projectKey=hellenjrubioc_DiagnoSys

# Organización en SonarCloud
sonar.organization=hellenjrubioc-diagnosys

# URL del servidor SonarCloud
sonar.host.url=https://sonarcloud.io

# Lenguaje del proyecto
sonar.language=ts

# Carpeta donde está el código fuente 
sonar.sources=src

# Carpeta con tests si aplica
# sonar.tests=tests

# Carpeta con archivos excluidos si aplica
# sonar.exclusions=node_modules/**,**/*.spec.ts
