name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    # Necesitamos darle permisos al token de GitHub para que pueda escribir/crear la rama de la página web
    permissions:
      contents: write
  
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Create temporary .env for build
        run: |
          echo "DATABASE_URL=\"${{ secrets.DATABASE_URL }}\"" >> .env
          echo "DATABASE_URL_DIRECT=\"${{ secrets.DATABASE_URL_DIRECT }}\"" >> .env
          echo "RESEND_API_KEY=\"${{ secrets.RESEND_API_KEY }}\"" >> .env
          echo "NEXTAUTH_SECRET=\"${{ secrets.NEXTAUTH_SECRET }}\"" >> .env
          echo "NEXT_PUBLIC_APP_URL=\"${{ secrets.NEXT_PUBLIC_APP_URL }}\"" >> .env

      - name: Build Application (Prisma + Next.js)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_URL_DIRECT: ${{ secrets.DATABASE_URL_DIRECT }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
        run: |
          npx prisma generate
          npm run build

      - name: Run Playwright tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_URL_DIRECT: ${{ secrets.DATABASE_URL_DIRECT }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
        run: npm run test:e2e

      # NUEVO PASO: Publica automáticamente el reporte HTML en GitHub Pages
      - name: Deploy Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always() # Queremos que publique el reporte tanto si pasan los tests como si fallan
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report